include: package:flutter_lints/flutter.yaml
linter:
    rules:
        - sort_pub_dependencies
analyzer:
    plugins:
        - custom_lint

custom_lint:
    rules:
        - avoid_manual_providers_as_generated_provider_dependency: false
