name: selene
description: 'A new Flutter project.'
publish_to: 'none'
version: 0.1.0

environment:
    sdk: ^3.7.0

dependencies:
    animated_visibility: ^0.0.4
    auto_route: ^9.2.2
    change_case: ^2.2.0
    cupertino_icons: ^1.0.8
    dartx: ^1.2.0
    draggable_menu: ^4.4.1
    drift: ^2.26.0
    drift_db_viewer: ^2.1.0
    drift_flutter: ^0.2.4
    dynamic_color: ^1.7.0
    flex_color_scheme: ^8.2.0
    flutter:
        sdk: flutter
    flutter_hooks: ^0.21.2
    flutter_riverpod: ^2.6.1
    flutter_svg: ^2.0.17
    freezed_annotation: ^2.4.4
    hooks_riverpod: ^2.6.1
    isar:
        version: 3.1.8
        hosted: https://pub.isar-community.dev/
    isar_flutter_libs: # contains Isar Core
        version: 3.1.8
        hosted: https://pub.isar-community.dev/
    json_annotation: ^4.9.0
    logger: ^2.5.0
    material_color_utilities: ^0.11.1
    material_symbols_icons: ^4.2811.0
    meta: ^1.16.0
    path_provider: ^2.1.5
    responsive_framework: ^1.5.1
    riverpod_annotation: ^2.6.1
    rxdart: ^0.28.0
    stream_transform: ^2.1.1
    system_theme: ^3.1.2

dev_dependencies:
    auto_route_generator: ^9.0.0
    build_runner: ^2.4.15
    custom_lint: ^0.7.0
    drift_dev: ^2.26.0
    flutter_lints: ^5.0.0
    flutter_test:
        sdk: flutter
    freezed: ^2.5.7
    isar_generator:
        version: 3.1.8
        hosted: https://pub.isar-community.dev/
    json_serializable: ^6.9.0
    package_rename: ^1.9.0
    riverpod_generator: ^2.3.3
    riverpod_lint: ^2.1.1

flutter:
    uses-material-design: true
    generate: true
    assets:
        - assets/
        - assets/fonts/
        - assets/icons/
        - assets/images/
        - assets/launcher/
        - assets/splash/

package_rename_config:
    android:
        app_name: Selene
        package_name: dev.nploetz.selene
        override_old_package: com.example.selene
        lang: kotlin
    ios:
        app_name: Selene
        bundle_name: selene
        package_name: dev.nploetz.selene
    linux:
        app_name: Selene
        package_name: dev.nploetz.selene
        exe_name: selene-linux-x64
    windows:
        app_name: Selene
        organization: nploetz
        copyright_notice: Copyright ©️ 2025 nploetz. All rights reserved.
        exe_name: selene-win32
    macos:
        app_name: Selene
        package_name: dev.nploetz.selene
        copyright_notice: Copyright ©️ 2025 nploetz. All rights reserved.
