// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB734ku6Px0p-wOB9LtpTZzGKaVzqNF9V4',
    appId: '1:66410332306:web:771ff81bc57818fe10664b',
    messagingSenderId: '66410332306',
    projectId: 'selene-049',
    authDomain: 'selene-049.firebaseapp.com',
    storageBucket: 'selene-049.firebasestorage.app',
    measurementId: 'G-0MB7FNGSWY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCgJ1G2izjBnDPhKWtGJhjGHcyJgB0IM-s',
    appId: '1:66410332306:android:fe26c5d89fc1554410664b',
    messagingSenderId: '66410332306',
    projectId: 'selene-049',
    storageBucket: 'selene-049.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAeMWjn86QzS69p1_YaLX12gFfhn9FWAGY',
    appId: '1:66410332306:ios:4f789de9a9ff209610664b',
    messagingSenderId: '66410332306',
    projectId: 'selene-049',
    storageBucket: 'selene-049.firebasestorage.app',
    iosBundleId: 'dev.nploetz.selene',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAeMWjn86QzS69p1_YaLX12gFfhn9FWAGY',
    appId: '1:66410332306:ios:4f789de9a9ff209610664b',
    messagingSenderId: '66410332306',
    projectId: 'selene-049',
    storageBucket: 'selene-049.firebasestorage.app',
    iosBundleId: 'dev.nploetz.selene',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB734ku6Px0p-wOB9LtpTZzGKaVzqNF9V4',
    appId: '1:66410332306:web:5bbef1268b8e612e10664b',
    messagingSenderId: '66410332306',
    projectId: 'selene-049',
    authDomain: 'selene-049.firebaseapp.com',
    storageBucket: 'selene-049.firebasestorage.app',
    measurementId: 'G-FLSRRELVCS',
  );

}